config/routes.rb
Rails.application.routes.draw do


  # makes devise look in the registrations controller for sign_up and account_update_params
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'proposals#index'

  # ':user_name' is a dynamic parameter, meaning we can pass in diffferent user_names's
  get 'users/:user_name', to: 'profiles#show', as: :profile
  get 'users/:user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch 'users/:user_name', to: 'profiles#update', as: :update_profile


  resources :proposals do
    resources :submissions do
      resources :comments
    end
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :user
belongs_to :submission
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :submissions
  validates :user_id, presence: true
  has_attached_file :avatar, styles: { large: "500x500>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/default-avatar.jpg"
validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  CATEGORIES = ['Web UX Design', 'Mobile Development (iOS)', 'Mobile Development (Android)', 'Mobile Development (Other)', 'Software Development', 'Web Development (Front-end)', 'Web Development (Server-side)', 'Web Development (Full-stack)', 'Other']
  LOCATIONS = ['Philadelphia', 'New York', 'Washington D.C', 'Boston', 'Chicago', 'Austin', 'Dallas', 'San Francisco', 'Los Angeles', 'San Diego', 'Seattle', 'Portland', 'Denver']
  DURATIONS = [7, 14, 30, 60, 90]
end

app/models/submission.rb
class Submission < ApplicationRecord

  validates :user_id, presence: true
  belongs_to :user
  belongs_to :proposal
  has_many :comments, dependent: :destroy
  has_attached_file :avatar, styles: { large: "500x500>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/default-avatar.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


end

app/models/user.rb
class User < ApplicationRecord


  enum access_level: [:contractor, :company]
  has_many :proposals, dependent: :destroy
  has_many :submissions, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }



  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #Paperclip shit
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/default-avatar.jpg"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_submission
before_action :set_user
before_action :set_proposal


  def index
    @comments = @submission.comments.all
  end

  def new
  end

    def create
        @comment = @submission.comments.build(comment_params)
        @comment.user_id = current_user.id
        if @comment.save
          redirect_to proposal_path(@proposal)
        else
          render root_path
        end
    end

    def destroy
      @comment = @submission.comments.find(params[:id])
      @comment.destroy
      redirect_to root_path
    end

    private

    def comment_params
      params.require(:comment).permit(:body)
    end

    def set_submission
      @submission = Submission.find(params[:submission_id])
    end

    def set_user
      @user = User.find_by(user_name: params[:user_name])
    end

    def set_proposal
      @proposal = Proposal.find(params[:proposal_id])
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :authenticate_user!
before_action :set_user
before_action :owned_profile, only: [:edit, :update]


  def show
    @user = User.find_by(user_name: params[:user_name])
  end

  def edit
    @user = User.find_by(user_name: params[:user_name])
  end

  def update
    @user = User.find_by(user_name: params[:user_name])
    if @user.update(profile_params)
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  private

  def profile_params
    params.require(:user).permit(:avatar, :bio, :access_level)
  end

  def set_user
    @user = User.find_by(user_name: params[:user_name])
  end

  def owned_profile
    unless current_user == @user
      flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
  end

end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController

  before_action :authenticate_user!


  before_action :authenticate_user!

  def index
    @proposals = Proposal.all
  end

# proposal is now built from the user instead of the proposal
  def new
    @proposal = current_user.proposals.build
  end

  def create
    @proposal = current_user.proposals.new(proposal_params)
    if @proposal.save
      redirect_to @proposal
    else
      render 'new'
  end
  end

  def edit
    @proposal = Proposal.find(params[:id])
  end

  def show
    @proposal = Proposal.find(params[:id])


  end

  def update
    @proposal = Proposal.find(params[:id])
    @proposal.update(proposal_params)
    redirect_to(proposal_path(@proposal))
  end

  def destroy
    @proposal = Proposal.find(params[:id])
    @proposal.destroy
    redirect_to proposals_path
  end

private

def proposal_params
  params.require(:proposal).permit(:avatar, :name, :short_desc, :fulldesc, :category, :location, :timelimit)
end

def set_proposal
  @proposal = Proposal.find(params[:id])
end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :access_level)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password, :access_level)
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
before_action :authenticate_user!
before_action :set_proposal


  def index
    @proposal = Proposal.find(params[:proposal_id])
    @submissions = Submission.all
  end

  def show
    @submission = Submission.find(params[:id])
  
  end

  def new
    @submission = Submission.new
  end

  def create
    @proposal = Proposal.find(params[:proposal_id])
    @submission = @proposal.submissions.new(submission_params)
    @submission.user_id = current_user.id

    if @submission.save!
      redirect_to proposal_path(@proposal)
    else
      render 'index'
    end
  end

  def edit
    @proposal = Proposal.find(params[:proposal_id])
    @submission = Submission.find(params[:id])
  end


    def update
      @submission = Submission.find(params[:id])
      if @submission.update(submission_params)
        redirect_to proposal_submission_path
      else
        render 'edit'
      end
    end

  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy
    redirect_to '/'

  end

private

def submission_params
  params.require(:submission).permit(:title, :description, :avatar)
end

def set_proposal
  @proposal = Proposal.find(params[:proposal_id])
end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController



  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


  def profile_avatar_select(user)
  return image_tag user.avatar.url(:medium),
                   id: 'image-preview',
                   class: 'img-responsive img-circle profile-image' if user.avatar.exists?
  image_tag 'default-avatar.jpg', id: 'image-preview',
                                  class: 'img-responsive img-circle profile-image'
end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Comment:</strong>
  <%= comment.content %>
</p>

<p>
  <%= link_to 'Delete Comment', [comment.submission, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <span class = "float_l"><%= link_to "Home", proposals_path %></span>
  <% if user_signed_in? %></span>

  <% if current_user.access_level != "contractor" %>
    <span class="float_r"><%= link_to "New Proposal", new_proposal_path %></span>
  <% end %>

    <span class="float_r"><%= link_to "Profile", profile_path(current_user.user_name) %></span>
    <span class="float_r"><%= link_to "Logout", destroy_user_session_path, method: :delete %></span>
  <% else %>
    <span class="float_r"><%= link_to "Login", new_user_session_path %></span>
    <span class="float_r"><%= link_to "Register", new_user_registration_path %></span>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Colosseum</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Spectral+SC" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= render 'layouts/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

  </body>
</html>

app/views/profiles/edit.html.erb
<div class="grid-item-3 center">
  <%= form_for @user, url: {action: "update"}, html: { multipart: true } do |f| %>
  <h3>Change your profile image:</h3>
          <%= profile_avatar_select(@user) %>

          <%= f.file_field :avatar, onChange: 'loadFile(event)' %>
  <h3>Update your bio:</h3>
    <%= f.text_area :bio, label: false, rows: 4 %><br/>
    <%= f.submit "Update Profile" %>
  <% end %>
</div>

app/views/profiles/show.html.erb
<div class="grid-item-4 pad_top">
  <% if @user == current_user %>
    <div style="float:left">
    <%= link_to 'Edit Profile', edit_profile_path(@user.user_name)%>
    <br/>
    <%= link_to "Account Settings", edit_user_registration_path%>
    </div>
  <% end %>
</div>

<div class="grid-item-3 center">
  <h2><%= link_to @user.user_name %></h2>
  <%= profile_avatar_select(@user) %>
  <br>
  <%= @user.bio %>
<div>

app/views/proposals/_form.html.erb
<%= form_with model: @proposal, local: true do |form| %>

<% if @proposal.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@proposal.errors.count, "error") %>
      prohibited this proposal from being saved:
    </h2>
    <ul>
      <% @proposal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>



<div class="form-field"><br>
  <p>Project Name</p>
  <%= form.text_field :name %>
</div>
<br>
<div class="form-field"><br>
  <p>Give your project a short description to bring in traffic!</p>
  <%= form.text_field 'short_desc', :maxlength => 40, :size => 40 %>
</div>
<br>
<div class="form-field">
  <p>How many days does this competition run?</p>
  <%= form.collection_select :timelimit, Proposal::DURATIONS, :to_i, :to_i %>
</div>
<br>
<div class="form-field"><br>
  <p>You've got their attention, now give 'em the details with a full run-down of exactly what you want. Be specific, and add links to outside resources! </p>
     <%= form.text_area 'fulldesc', :size => '60x10', :class => 'longdesc' %>
</div>
<br>
<div class="form-field">
  <p>What aspect of your business do you need help with? If a category you'd like isn't displayed, select Other, or contact us directly.</p>
  <%= form.collection_select :category, Proposal::CATEGORIES, :to_s, :to_s,
       :include_blank => true %>
</div>
<br>
<div class="form-field">
  <p>Is your project based out of a specific location? Feel free to leave this blank if not.</p>
  <%= form.collection_select :location, Proposal::LOCATIONS, :to_s, :to_s,
       :include_blank => true %>
</div>
<br>
<div class="form-field">
  <p>Got some assets to give people a head-start with? Upload them here!</p>
  <%= form.file_field :avatar %>
</div>
<br>
<br>
<div class="form-field">
  <%= form.submit %>
</div>

<% end %>

app/views/proposals/_proposal.html.erb
<%-# THIS IS THE INDIVIDUAL PROPOSAL# SHOW PARTIAL  -%>

<%-# USER AVATAR IMAGE THAT IS ALSO A LINK GOES BELOW-%>
<%= link_to image_tag(proposal.user.avatar.url(:thumb)), profile_path(proposal.user.user_name) %>

<div class="grid-item-2">
  <h2><%= proposal.name %></h2>

  <div class="prop-attr-box">
    <div class="cate">CATEGORY:<br><%= proposal.category %></div>
    <div class="loc">LOCATION:<br><%= proposal.location %></div>
  </div>

  <div class="time-left-box">
    DURATION:<br><%= proposal.timelimit %>
    DAYS
  </div>
</div>

<div class="prop-fdesc-box">
  <p><%= proposal.fulldesc %></p>
</div>

<small>Proposed
  <%= time_ago_in_words(proposal.created_at) %>
  ago by
  <%=  link_to proposal.user.user_name, profile_path(proposal.user.user_name) %></small>

<br>
</div>


<div class="grid-item-6">
<%= link_to image_tag(proposal.avatar.url(:large)), proposal_path(proposal) %>
</div>

<h3>CURRENT SUBMISSIONS</h3>
<% if proposal.submissions.any? %>
<% proposal.submissions.each do |submission| %>

<ul><%= link_to submission.user.user_name, profile_path(proposal.user.user_name) %>
-
<a href='/proposals/<%= proposal.id %>/submissions/<%=submission.id %>'>
  <%=submission.title %></a>
</ul>

<% if submission.user == current_user %>

<span><%= link_to proposal_submission_path(proposal, submission), method: :delete, data: { confirm: "Are you sure?" } do %></span>
<% end %>
<% end %>
<% end %>
<% end %>
<% if ((proposal.created_at + proposal.timelimit.days) - Time.now) > 0 && current_user.access_level == "contractor"%>

<div class="submission-add-box">
<h3>Add A Submission?</h3>
<%= form_for [proposal, proposal.submissions.new] do |f| %>
<ul>
  <%= f.file_field :avatar %>
  <%= f.text_field :title, placeholder: 'Submission Title' %>
  <%= f.text_field :description, placeholder:  'Add the description...' %>
  <%=f.submit 'Submission'%>
</ul>
<% end %>
<% if ((proposal.created_at + proposal.timelimit.days) - Time.now) < 1 && current_user.access_level = "contractor" %>
<div class="submission-add-box">

  <button class="patty">
    Choose Winner
  </button>
</div>
<% end %>
</div>
<% end %>

app/views/proposals/_proposalIndex.html.erb
<div class="box">
  <h2 class = "normal"><%= proposal.name %></h2>
        <%-# USER AVATAR IMAGE THAT IS ALSO A LINK -%>

  <%= link_to image_tag(proposal.user.avatar.url(:thumb)), proposal_path(proposal.id) %>
    <small>Proposed <%= time_ago_in_words(proposal.created_at) %> ago by <%=  proposal.user.user_name %></small>
    <p ><%= proposal.short_desc %></p>

    <% if (proposal.created_at + proposal.timelimit.days - Time.now) > 0 %>
      <p >Time Remaining: <%=  ((proposal.created_at + proposal.timelimit.days - Time.now)/86400).round %> Days</p>
    <% else %>
      <p> This event has ended, the winner will be chosen shortly </p>
    <% end %>

    <br>
    <div class = "textBackground"><%= link_to "View Proposal", proposal_path(proposal.id) %></div>
    <br>
</div>

app/views/proposals/edit.html.erb
<h1>EDIT PROPOSAL</h1>

<%= render 'form' %>

app/views/proposals/index.html.erb
<div class="grid-item-3 top">
  <h2 class="center">PROPOSALS INDEX</h2>
  <% @proposals.each do |proposal| %>
    <%= render 'proposalIndex', proposal: proposal %>
  <% end %>
</div>

app/views/proposals/new.html.erb
<div class="grid-item-2 pad_l">
  <h1>NEW PROPOSAL!</h1>
  <%= render 'form' %>
</div>

<div class="grid-item-3 pad_top float_l">
  <button><%= link_to 'Back', proposals_path %></button>
</div>

app/views/proposals/show.html.erb
<%= render 'proposal', proposal: @proposal %>
<div class="grid-item-4">
  <h3>Project Resources:</h3>
  <ul>
    <li><%= link_to "Return to Proposal Index", proposals_path %></li>
    <% if @proposal.user.id == current_user.id %>
    <li><%= link_to "Edit Proposal", edit_proposal_path(@proposal) %></li>
    <li><%= link_to 'Destroy', @proposal, :method => :delete %></li>
    <% end %>
  </ul>
</div>

app/views/submissions/_form.html.erb
<%= form_with(model: [ @proposal, @proposal.submissions.build ]) do |form| %>

  <p><%= form.file_field :avatar %></p>

  <p><%= form.label :title %> <br> <%= form.text_area :title %></p>

  <p><%= form.label :description %> <br> <%= form.text_area :description %></p>

  <p><%= form.submit %></p>

  <% end %>

app/views/submissions/_submission.html.erb
<%-# THIS IS THE INDIVIDUAL SUBMISSION# SHOW PARTIAL  -%>



<%= image_tag @submission.avatar.url(:medium) %>

  <h2><%= @submission.title %></h2>

  <h4>Description: <%= submission.description %></h4>
  <small>Submitted <%= time_ago_in_words(submission.created_at) %> ago by <%=  link_to submission.user.email, profile_path(submission.user.user_name) %></small>

  <br>

  <% if @submission.user == current_user %>
  <span><%= link_to "Edit Submission", edit_proposal_submission_path %> -
  <%= link_to 'Destroy', proposal_submission_path, :method => :delete %></span>
  <% end %>
  <hr>

  <%= form_for([@proposal, @submission,  @submission.comments.new]) do |f| %>
      <%= f.text_field :body, placeholder: 'Add a comment...' %>
      <%= f.submit %>

  <% end %>

  <br>

<div>
  <h3>Comments:</h3>
  <% if submission.comments %>
    <% submission.comments.each do |comment| %>
      <ul><%= link_to comment.user_id, profile_path(submission.user.user_name) %></ul>
    <ul><%= comment.body %></ul>

<% end %>
<% end %>
  </div>
  <hr>

app/views/submissions/edit.html.erb
<h1>EDIT Submission</h1>

<%= form_for @submission, url: proposal_submission_path do |f| %>

<li><%= f.file_field :avatar %></li>
<li><%= f.text_field :title %></li>
<li> <%= f.text_field :description,
placeholder:  'Add the description...' %>
<li> <%=f.submit 'Submission'%></li>


<% end %>


<%= link_to 'Back', proposal_submission_path %>

app/views/submissions/index.html.erb
<h1>SUBMISSIONS</h1>
<% @submissions.each do |submission| %>
<li><a href='/proposals/<%= @proposal.id %>/submissions/<%=submission.id %>' ><%=submission.title %></a></li>
<%= submission.description %>
<%= submission.avatar %>
<% end %>

app/views/submissions/new.html.erb
<h1>NEW SUBMISSION!</h1>

<%= render 'form' %>

app/views/submissions/show.html.erb
<h2><%= @submission.user.user_name %>'s submission</h2>
  <%= render 'submission', submission: @submission %>

app/views/welcome/index.html.erb
<h1>Colosseum</h1>
<%= link_to "Colosseum" %>